### ISSUE TITLE
File unreadable

### ISSUE THREAD

**Issue by jrock2004** [kaermorchen/ember-cli-bootstrap-4#10]
Just installed the plugin via your instructions on the readme and I am getting the following error

```
Build failed.
File: /home/jcostanzo/Development/whylinuxisbetter/tmp/sass_compiler-input_base_path-RRzyTW1E.tmp/app/styles/app.scss (1)
The Broccoli Plugin: [SassCompiler] failed with:
Error: File to import not found or unreadable: ember-cli-bootstrap-4/bootstrap-flex
Parent style sheet: /home/jcostanzo/Development/whylinuxisbetter/tmp/sass_compiler-input_base_path-RRzyTW1E.tmp/app/styles/app.scss
    at options.error (/home/jcostanzo/Development/whylinuxisbetter/node_modules/node-sass/lib/index.js:286:26)

The broccoli plugin was instantiated at: 
    at SassCompiler.Plugin (/home/jcostanzo/Development/whylinuxisbetter/node_modules/broccoli-plugin/index.js:7:31)
    at SassCompiler.CachingWriter [as constructor] (/home/jcostanzo/Development/whylinuxisbetter/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/index.js:18:10)
    at new SassCompiler (/home/jcostanzo/Development/whylinuxisbetter/node_modules/broccoli-sass-source-maps/index.js:20:17)
    at /home/jcostanzo/Development/whylinuxisbetter/node_modules/ember-cli-sass/index.js:39:12
    at Array.map (native)
    at SASSPlugin.toTree (/home/jcostanzo/Development/whylinuxisbetter/node_modules/ember-cli-sass/index.js:36:34)
    at /home/jcostanzo/Development/whylinuxisbetter/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (/home/jcostanzo/Development/whylinuxisbetter/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
    at module.exports.preprocessCss (/home/jcostanzo/Development/whylinuxisbetter/node_modules/ember-cli-preprocess-registry/preprocessors.js:148:10)

```

**Comment by kaermorchen** [comment]
Hello.

You need to create the file `app/styles/app.scss`

**Comment by kaermorchen** [comment]
I close it. But feel free to reopen it.
