### ISSUE TITLE
Fix build project ember cli 2.14

### ISSUE THREAD

**Issue by jeffliveco** [kaermorchen/ember-cli-bootstrap-4#14]
Cannot find module 'tether/package.json' from '/Users/jeffersonortiz/Documents/proyects/geek-developers/qcams/admin-marketing/node_modules/ember-cli-bootstrap-4'

Error: Cannot find module 'tether/package.json' from '/Users/jeffersonortiz/Documents/proyects/geek-developers/qcams/admin-marketing/node_modules/ember-cli-bootstrap-4'
    at Function.module.exports [as sync] (/Users/jeffersonortiz/Documents/proyects/geek-developers/qcams/admin-marketing/node_modules/resolve/lib/sync.js:40:15)
    at npmTree (/Users/jeffersonortiz/Documents/proyects/geek-developers/qcams/admin-marketing/node_modules/ember-cli-node-assets/lib/tree-for.js:47:42)
    at processedTree (/Users/jeffersonortiz/Documents/proyects/geek-developers/qcams/admin-marketing/node_modules/ember-cli-node-assets/lib/tree-for.js:38:14)
    at /Users/jeffersonortiz/Documents/proyects/geek-developers/qcams/admin-marketing/node_modules/ember-cli-node-assets/lib/tree-for.js:28:14
    at Array.map (native)
    at /Users/jeffersonortiz/Documents/proyects/geek-developers/qcams/admin-marketing/node_modules/ember-cli-node-assets/lib/tree-for.js:27:22
    at Array.map (native)
    at treeFor (/Users/jeffersonortiz/Documents/proyects/geek-developers/qcams/admin-marketing/node_modules/ember-cli-node-assets/lib/tree-for.js:23:24)
    at Class.treeForVendor (/Users/jeffersonortiz/Documents/proyects/geek-developers/qcams/admin-marketing/node_modules/ember-cli-node-assets/index.js:18:37)
    at Class._treeFor (/Users/jeffersonortiz/Documents/proyects/geek-developers/qcams/admin-marketing/node_modules/ember-cli/lib/models/addon.js:520:33)

**Comment by kaermorchen** [comment]
Looks like you don't have installed bootstrap and tether. Try this:
`ember g ember-cli-bootstrap-4`
or
`npm i bootstrap@v4.0.0-alpha.6 --save-dev`

**Comment by NickBeukema** [comment]
I found that installing ember-tether fixes this problem.

`ember install ember-tether`

**Comment by jeffliveco** [comment]
thx so much, it worked.
