### ISSUE TITLE
Missing dependency on install 

### ISSUE THREAD

**Issue by temecom** [kaermorchen/ember-cli-bootstrap-4#15]
After following the install instructions I get a missing dependency error: 

Cannot find module 'tether/package.json' from 'D:\Development\picsie-baseline\node_modules\ember-cli-bootstrap-4'
Error: Cannot find module 'tether/package.json' from 'D:\Development\picsie-baseline\node_modules\ember-cli-bootstrap-4'
    at Function.module.exports [as sync] (D:\Development\picsie-baseline\node_modules\resolve\lib\sync.js:40:15)
    at npmTree (D:\Development\picsie-baseline\node_modules\ember-cli-node-assets\lib\tree-for.js:47:42)
    at processedTree (D:\Development\picsie-baseline\node_modules\ember-cli-node-assets\lib\tree-for.js:38:14)
    at D:\Development\picsie-baseline\node_modules\ember-cli-node-assets\lib\tree-for.js:28:14
    at Array.map (native)
    at D:\Development\picsie-baseline\node_modules\ember-cli-node-assets\lib\tree-for.js:27:22
    at Array.map (native)
    at treeFor (D:\Development\picsie-baseline\node_modules\ember-cli-node-assets\lib\tree-for.js:23:24)
    at Class.treeForVendor (D:\Development\picsie-baseline\node_modules\ember-cli-node-assets\index.js:18:37)
    at Class._treeFor (D:\Development\picsie-baseline\node_modules\ember-cli\lib\models\addon.js:551:33)

Installing tether solves this one but then the application fails with:

 Uncaught Error: Bootstrap dropdown require Popper.js (https://popper.js.org)
    at bootstrap.js:1414
    at bootstrap.js:1823
    at bootstrap.js:3830
loader.js:247Uncaught Error: Could not find module `ember-resolver` imported from `picsie-baseline/resolver`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at requireModule (loader.js:24)
    at app-boot.js:2

$ ember --version
ember-cli: 2.14.2
node: 6.9.1
os: win32 x64

**Comment by beerlington** [comment]
@temecom it appears this add on isn't compatible with the beta version of bootstrap 4. I was able to resolve it temporarily by fixing the version of bootstrap in my bower.json file to an alpha version.

**Comment by kaermorchen** [comment]
Fixed in latest version (0.3.0)
