### ISSUE TITLE
Error: File to import not found or unreadable: ember-cli-bootstrap-4/custom

### ISSUE THREAD

**Issue by rossjha** [kaermorchen/ember-cli-bootstrap-4#16]
Hey, i'm getting the following error when attempting a build.  Any ideas?

```
ember-cli: 2.11.0
node: 6.11.0
os: darwin x64
```

```
Build failed.
The Broccoli Plugin: [BroccoliMergeTrees] failed with:
Error: File to import not found or unreadable: ember-cli-bootstrap-4/custom

Parent style sheet: /Users/rossjha/gmc/tmp/sass_compiler-input_base_path-YTXzgrHG.tmp/app/styles/bootstrap.scss
    at options.error (/Users/rossjha/gmc/node_modules/node-sass/lib/index.js:286:26)

The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (/Users/rossjha/gmc/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/rossjha/gmc/node_modules/broccoli-merge-trees/index.js:42:10)
    at BroccoliMergeTrees (/Users/rossjha/gmc/node_modules/broccoli-merge-trees/index.js:36:53)
    at SASSPlugin.toTree (/Users/rossjha/gmc/node_modules/ember-cli-sass/index.js:42:10)
    at /Users/rossjha/gmc/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (/Users/rossjha/gmc/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
    at module.exports.preprocessCss (/Users/rossjha/gmc/node_modules/ember-cli-preprocess-registry/preprocessors.js:148:10)
    at EmberApp.styles (/Users/rossjha/gmc/node_modules/ember-cli/lib/broccoli/ember-app.js:1346:28)
    at EmberApp.toArray (/Users/rossjha/gmc/node_modules/ember-cli/lib/broccoli/ember-app.js:1675:10
```

**Comment by kaermorchen** [comment]
Hi.

Bootstrap don't have custom.scss. In your bootstrap.scss change the line `@import "ember-cli-bootstrap-4/custom"` => `@import "custom"` and store you custom variables in `/app/styles/custom.scss`
