### ISSUE TITLE
Cannot read property 'project' of undefined

### ISSUE THREAD

**Issue by csprocket777** [kaermorchen/ember-cli-bootstrap-4#2]
I just did a new ember app. First install was ember-cli-bootstrap-4.
Went to run it and got the following error right out of the gate:
```
Cannot read property 'project' of undefined
TypeError: Cannot read property 'project' of undefined
    at CoreObject.module.exports.sassOptions ([pathToProject]/node_modules/ember-cli-bootstrap-4/node_modules/ember-cli-sass/index.js:59:47)
    at SASSPlugin.toTree ([pathToProject]/node_modules/ember-cli-bootstrap-4/node_modules/ember-cli-sass/index.js:15:32)
    at [pathToProject]/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins ([pathToProject]/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at module.exports.preprocessCss ([pathToProject]/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:152:10)
    at CoreObject.extend.compileStyles ([pathToProject]/node_modules/ember-cli/lib/models/addon.js:547:14)
    at CoreObject.extend.treeForAddon ([pathToProject]/node_modules/ember-cli/lib/models/addon.js:440:27)
    at CoreObject._treeFor ([pathToProject]/node_modules/ember-cli/lib/models/addon.js:358:33)
    at CoreObject.treeFor ([pathToProject]/node_modules/ember-cli/lib/models/addon.js:326:21)
```

Am I doing something wrong?

**Comment by csprocket777** [comment]
I changed
```
Line 59: 
options.sourceMapRoot = path.join(this.app.project.root, 'app/styles');
```
to
```
Line 59:
options.sourceMapRoot = path.join(this.project.root, 'app/styles');
```

and it compiled. Am I breaking something by doing this?

**Comment by kaermorchen** [comment]
Hello @csprocket777 

Sorry, but I don't understand how catch you this error. I created new ember app, installed ember-cli-bootstrap-4 and all work how expected.
