### ISSUE TITLE
Add support for addons. 

### ISSUE THREAD

**Issue by demee** [kaermorchen/ember-cli-bootstrap-4#21]
Create new ember addon: 

`ember new --blueprint addon fancy-form`

Install extention: 
`cd fancy-form/`
`ember install --save ember-cli-bootstrap-4`

Try to start server: 

`ember server`

An exception is thrown: 

    TypeError: Cannot read property 'options' of undefined
        at Class.included (./node_modules/ember-cli-bootstrap-4/index.js:21:62)
        at Class.superWrapper [as included] (./node_modules/core-object/lib/assign-properties.js:34:20)
        at addons.reduce (./node_modules/ember-cli/lib/models/addon.js:384:26)
        at Array.reduce (<anonymous>)
        at Class.eachAddonInvoke (./node_modules/ember-cli/lib/models/addon.js:381:24)
        at Class.included (./node_modules/ember-cli/lib/models/addon.js:657:10)
        at Class.superWrapper [as included] (./node_modules/core-object/lib/assign-properties.js:34:20)
        at project.addons.project.addons.filter.addon (./node_modules/ember-cli/lib/broccoli/ember-app.js:545:17)
        at Array.filter (<anonymous>)
        at EmberAddon._notifyAddonIncluded (./node_modules/ember-cli/lib/broccoli/ember-app.js:542:47)

**Comment by kaermorchen** [comment]
Hello.

Fixed in latest vesion (0.4.2).
