### ISSUE TITLE
Found an unknown transformation name fastbootShim

### ISSUE THREAD

**Issue by belgoros** [kaermorchen/ember-cli-bootstrap-4#30]
After installing the add-on and booting the newly created app, I got the below error:
```
while import node_modules/popper.js/dist/umd/popper.js: found an unknown transformation name fastbootShim. Available transformNames are: amd


Stack Trace and Error Report: /var/folders/jr/kxc055h933qbrrqbm8gwq3s00000gp/T/error.dump.0e4918558029f60a0be217404fab0497.log
```
Full error stack trace from the `log` file:
```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: while import node_modules/popper.js/dist/umd/popper.js: found an unknown transformation name fastbootShim. Available transformNames are: amd
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: while import node_modules/popper.js/dist/umd/popper.js: found an unknown transformation name fastbootShim. Available transformNames are: amd
.....
```
What's wrong with `popper.js` installation ?
Here is my config:
```
ember-cli: 2.18.2
node: 8.9.1
os: darwin x64
```

**Comment by kaermorchen** [comment]
Should be fixed in latest (v0.5.4) version.

**Comment by belgoros** [comment]
Not yet:
```
embercli-bootsrtap4 git:(master) ✗ ember s
while import node_modules/popper.js/dist/umd/popper.js: found an unknown transformation name fastbootShim. Available transformNames are: amd


Stack Trace and Error Report: /var/folders/jr/kxc055h933qbrrqbm8gwq3s00000gp/T/error.dump.53f733f051a3c5c4753ecb5dfb0501fc.log
```
Log file content:
```
ENV Summary:

  TIME: Sun Feb 11 2018 20:35:20 GMT+0100 (CET)
  TITLE: ember
  ARGV:
  - /usr/local/Cellar/node/8.9.1/bin/node
  - /usr/local/bin/ember
  - s
  EXEC_PATH: /usr/local/Cellar/node/8.9.1/bin/node
  TMPDIR: /var/folders/jr/kxc055h933qbrrqbm8gwq3s00000gp/T
  SHELL: /bin/zsh
  PATH:
  - /Users/serge-mac/.rvm/gems/ruby-2.4.0/bin
  - /Users/serge-mac/.rvm/gems/ruby-2.4.0@global/bin
  - /Users/serge-mac/.rvm/rubies/ruby-2.4.0/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /opt/X11/bin
  - /usr/local/git/bin
  - /Applications/Postgres.app/Contents/Versions/latest/bin
  - /Users/serge-mac/.rvm/bin
  PLATFORM: darwin x64
  FREEMEM: 324435968
  TOTALMEM: 4294967296
  UPTIME: 171
  LOADAVG: 13.7177734375,13.29541015625,6.1533203125
  CPUS:
  - Intel(R) Core(TM) i5-2467M CPU @ 1.60GHz - 1600
  - Intel(R) Core(TM) i5-2467M CPU @ 1.60GHz - 1600
  - Intel(R) Core(TM) i5-2467M CPU @ 1.60GHz - 1600
  - Intel(R) Core(TM) i5-2467M CPU @ 1.60GHz - 1600
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 31.0.1
  - http_parser: 2.7.0
  - icu: 59.1
  - modules: 57
  - nghttp2: 1.25.0
  - node: 8.9.1
  - openssl: 1.0.2m
  - tz: 2017b
  - unicode: 9.0
  - uv: 1.15.0
  - v8: 6.1.534.47
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: while import node_modules/popper.js/dist/umd/popper.js: found an unknown transformation name fastbootShim. Available transformNames are: amd
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: while import node_modules/popper.js/dist/umd/popper.js: found an unknown transformation name fastbootShim. Available transformNames are: amd
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: while import node_modules/popper.js/dist/umd/popper.js: found an unknown transformation name fastbootShim. Available transformNames are: amd
    at options.using.forEach.entry (/Users/serge-mac/Development/embercli-bootsrtap4/node_modules/ember-cli/lib/broccoli/ember-app.js:1724:19)
    at Array.forEach (<anonymous>)
    at EmberApp._import (/Users/serge-mac/Development/embercli-bootsrtap4/node_modules/ember-cli/lib/broccoli/ember-app.js:1715:23)
    at EmberApp.import (/Users/serge-mac/Development/embercli-bootsrtap4/node_modules/ember-cli/lib/broccoli/ember-app.js:1688:10)
    at Class.included (/Users/serge-mac/Development/embercli-bootsrtap4/node_modules/ember-cli-bootstrap-4/index.js:29:17)
    at Class.superWrapper [as included] (/Users/serge-mac/Development/embercli-bootsrtap4/node_modules/core-object/lib/assign-properties.js:34:20)
    at project.addons.project.addons.filter.addon (/Users/serge-mac/Development/embercli-bootsrtap4/node_modules/ember-cli/lib/broccoli/ember-app.js:555:17)
    at Array.filter (<anonymous>)
    at EmberApp._notifyAddonIncluded (/Users/serge-mac/Development/embercli-bootsrtap4/node_modules/ember-cli/lib/broccoli/ember-app.js:552:47)
    at new EmberApp (/Users/serge-mac/Development/embercli-bootsrtap4/node_modules/ember-cli/lib/broccoli/ember-app.js:166:10)
```
I can push to Github repo if needed.

**Comment by kaermorchen** [comment]
I think I have fixed it. 

v0.5.5

**Comment by belgoros** [comment]
👍 Thanks a lot, it works like a charm !
